<?php

namespace OpenWorld\Data\FileLoaderResults;

use OpenWorld\Data\AbstractClasses\FileLoaderResultAbstract;

/**
 * Class JsonFileLoaderResult
 * 
 * Provides access to loaded json data.
 * 
 * @package OpenWorld\Data\FileLoaderResults
 */
class JsonFileLoaderResult extends FileLoaderResultAbstract {

    public function asString(): string
    {
        parent::asString(); // TODO: Change the autogenerated stub
    }

    public function asArray() : array
    {
        parent::asArray(); // TODO: Change the autogenerated stub
    }

    public function asObject() : Object
    {
        parent::asObject(); // TODO: Change the autogenerated stub
    }

    public function isValid($content) : bool
    {
        // TODO: Implement isValid() method.
    }
}